on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Input release mode, "normal" or "prerelease".'
        required: true
        default: ''

jobs:
  start_release:
    if: github.event.inputs.mode == 'normal' || github.event.inputs.mode == 'prerelease'
    runs-on: ubuntu-latest
    env:
      RESULT_PATH: /tmp/result.txt
      IS_PRERELEASE: ${{ github.event.inputs.mode == 'prerelease' }}
      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: push branch
        run: |
          git checkout -b release-candidate
          git push origin release-candidate
          
      - name: release dry run
        run: echo hoge > ${{ env.RESULT_PATH }}} 
      - name: wrap dry run log
        run: |
          echo "Dry Run Log:
          \`\`\`
          $(cat ${{ env.RESULT_PATH }})
          \`\`\`" > ${{ env.RESULT_PATH }}
      - name: create issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Release candidate
          content-filepath: ${{ env.RESULT_PATH }}
          labels: release candidate
