on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Input release mode, "normal" or "prerelease".'
        required: true
        default: ''

jobs:
  start_release:
    if: github.event.inputs.mode == 'normal' || github.event.inputs.mode == 'prerelease'
    runs-on: ubuntu-latest
    env:
      RESULT_PATH: /tmp/result.txt
      IS_PRERELEASE: ${{ github.event.inputs.mode == 'prerelease' }}
